### ISSUE TITLE
Improve Form UI

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/webrtc-client#16]
<img width="747" alt="Screenshot 2024-10-05 at 7 00 42 PM" src="https://github.com/user-attachments/assets/0c298e51-4b9d-4166-a6ae-25a4eaa6dafc">

Ref - https://github.com/manzil-infinity180/webrtc-client/blob/main/src/components/ZoomSdk.jsx

**Comment by Ansh101112** [comment]
assign me this issue
@manzil-infinity180
